name: A workflow for my Hello World file
on:
  pull_request:
    branches: [ main ]
jobs:
  prep:
    name: Create Pipeline
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: GH-Action
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: pipeline-stack
          template: pipeline-stack.yml
          parameter-overrides: "CodePipelineName=GH-PR-pipeline,S3BucketName=gh-source-artifact,LogBucketName=gh-build-artifact,GithubOwner=wellsiau-aws,GithubRepo=test-pull-request,GithubBranch=main,GithubToken=${{ secrets.REPO_ACCESS_TOKEN }}"